name: blueprint_project_flutter
description: Enterprise Clean Architecture & BLoC Flutter Blueprint
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  app_ui:
    path: ./packages/app_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mocktail: ^1.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
